from . import _u
WEAPONS = _u.WEAPONS
WeaponDef = _u.WeaponDef
STARTING_OWNED = _u.STARTING_OWNED
STARTING_RANGED = _u.STARTING_RANGED
STARTING_MELEE = _u.STARTING_MELEE
STARTING_MISC_A = _u.STARTING_MISC_A
STARTING_MISC_B = _u.STARTING_MISC_B
